---
- name: Facts Explorer
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Show hostname
      debug:
        var: ansible_hostname

    - name: Show operating system
      debug:
        var: ansible_distribution

    - name: Show architecture
      debug:
        var: ansible_architecture

    - name: Show Python version
      debug:
        var: ansible_python_version

    - name: Show all IPv4 addresses (if available)
      debug:
        var: ansible_all_ipv4_addresses
      when: ansible_all_ipv4_addresses is defined

    - name: Show network interfaces
      debug:
        var: ansible_interfaces
      when: ansible_interfaces is defined
