---
- name: Collect System Information
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname is {{ ansible_hostname }}"

    - name: Display operating system
      ansible.builtin.debug:
        msg: "Operating system is {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display Python version
      ansible.builtin.debug:
        var: ansible_python_version

    - name: Display architecture
      ansible.builtin.debug:
        var: ansible_architecture

    - name: Display IPv4 addresses
      ansible.builtin.debug:
        var: ansible_all_ipv4_addresses
      when: ansible_all_ipv4_addresses is defined

    - name: Display network interfaces
      ansible.builtin.debug:
        var: ansible_interfaces
      when: ansible_interfaces is defined
