name: Ansible CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ansible-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Check YAML syntax
        run: |
          yamllint ansible/

      - name: Ansible syntax check
        run: |
          ansible-playbook \
          --syntax-check \
          ansible/playbooks/*.yaml

      - name: Run ansible-lint
        run: |
          ansible-lint ansible/playbooks/